### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by alanludke** [EDGutterres/trabalho_formais#3]
**TODO METHODS**
- [x] make_tree(regex):
- [x] split_elements(regex):
- [x] get_internal_regex(regex):
- [x] split_tree(list=elements):
- [x] search_incomplete_nodes(Node=node, bool=tree_unfinished)
- [x] optimize(Node=node)
- [x] set_leaf_nodes_values(Node=node, int=pos)
- [x] generate_first_last_pos(Node=node)
- [ ] generate_followpos(Node=node)
- [x] post_order(Node=node)
- [x] create_af_from_tree(Node=node)

**Comment by alanludke** [comment]
create_af_from_tree => getAutomataFromTree
